version: "3.9"
services:
  app:
    image: node:20
    container_name: portfolio
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "node server.js"