name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Set image name
      - name: Set image name
        run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/portfolio" >> $GITHUB_ENV

      # Extract git tag (example: v0.2.1)
      - name: Extract tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Build image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:latest .

      # Push version tag
      - name: Push version image
        run: docker push $IMAGE_NAME:$VERSION

      # Push latest tag
      - name: Push latest image
        run: docker push $IMAGE_NAME:latest